name: Deploy to GHCR (Worker)

on:
  push:
    branches:
      - master
    paths:
      - 'worker/**'
      - '.github/workflows/deploy_worker.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to GHCR
      uses: docker/build-push-action@v1
      with:
        repository: nint8835/terraform-gatsby-service-worker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ghcr.io
        tags: latest
        path: ./worker
        dockerfile: ./worker/Dockerfile
