name: Deploy to Docker Hub (Worker)

on:
  push:
    branches:
      - master
    paths:
      - 'worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Hub (Worker)
      uses: docker/build-push-action@v1
      with:
        repository: nint8835/terraform-gatsby-service-worker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        dockerfile: ./worker/Dockerfile
